[workspace]
members = ["verifier", "registry"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
alloy-primitives = "1.5.7"
alloy-sol-types = "1.5.7"
stylus-sdk = "0.10.9"
ed25519-dalek = "2"

# Size-optimized release builds for on-chain WASM.
[profile.release]
codegen-units = 1
strip = true
lto = true
panic = "abort"
opt-level = "z"
